### ISSUE TITLE
[Feat] Add UI for submitting subjects

### ISSUE THREAD

**Issue by Harini-Sritharar** [drp08/StudyPal#19]
# User Story

As a student, I want to submit my subjects and be told when to study a topic so that I don not waste time deciding what to study.

# Technical Implementation

Create a UI screen for submitting projects. This includes
- A floating action button in the Home and/or Calendar screen.
- An expandable floating action button to expand to show "Add Subject"
- A screen view with the form and a submit button.

**Comment by cybercoder-naj** [comment]
Requires #8
